# Syntax
# //list of configurations
#   - <conf_item>*  // configuration item (any name)
#      symbol: <symbol>
#      interval: <interval> on of 1s 1m 3m 5m 15m 30m 1h 2h 4h  6h 8h 12h  1d 3d 1w 1mo
#      history_start_date: <a date> in the format yyyy-mm-dd
#      history_end_date: <a date> in the format yyyy-mm-dd or 'now' for yesterday date
#      destination_dir: path   path where to save downloaded data
DataDatabase:
    instance_name: postgres
    host: 3.252.122.34
    port: 5432
    username: postgres
    password: postgres

AppDatabase:
    instance_name: postgres
    host: 3.252.122.34
    port: 5432
    username: postgres
    password: postgres

Models:
    dir: /tmp/

Pairs:
    - BTCUSDT:
        symbol: BTCUSDT
        description: 'BTC: Bitcoin, USDT: TetherUS'
        interval: 1d
        history_start_date: 2017-08-01
        history_end_date: now
        destination_dir: data

    #- ETHUSDT:
    #    symbol: ETHUSDT
    #    interval: 1m
    #    history_start_date: 2017-01-01
    #    history_end_date: now
    #    destination_dir: data

    #- DOGEUSDT:
    #    symbol: DOGEUSDT
    #    interval: 1m
    #    history_start_date: 2017-01-01
    #    history_end_date: now
    #    destination_dir: data
