version: '3.1'

services:
  timescaledb:
    container_name: db_container
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  history:
    container_name: get_history_container
    build:
      context: ./data/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs:/var/log
    ports:
      - 8000:8000
    depends_on:
      - timescaledb
    networks:
      - app-network
    
  fastapi:
    container_name: fastapi_container
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - timescaledb
    links:
      - timescaledb
    networks:
      - app-network

  streamlit:
    container_name: streamlit_container
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge