services:
  postgres:
    container_name: CryptoBot
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8077:8080
volumes:
  pgdata:        
